### ISSUE TITLE
Problems with Å

### ISSUE THREAD

**Issue by moewew** [plk/biber#190]
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
  @misc{aa,author = {Å}}
  @misc{laa,author = {lÅ}}
  @misc{aal,author = {Ål}}
\end{filecontents}

\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
throws a warning along the lines of
```
warning: undefined macro "Ã"
```
for the entry `aa` with Biber 2.8 on Windows 10 (MikTeX) and Ubuntu 17.10 (TeX live 2017).
The entries `aal` and `laa` are fine. So there seems to be a problem if the only character in a field is 'Å'.

**Comment by plk** [comment]
This is one of those weird edge cases with the somewhat primitive UTF-8 awareness I hacked into the btparse C library.  I could revisit it at some point but I'm not sure it's worth it as it only seems to be an issue in cases like this which aren't likely to occur in practice.

**Comment by moewew** [comment]
Mhhh, OK. It used to work at some point, though: https://tex.stackexchange.com/q/65161/35864
But you are right the case is definitely quite edgy.

**Comment by plk** [comment]
By the way, this works with quotes instead of braces. I will release biber 2.9 shortly due to a bug with tool mode which I missed in my test cases.

**Comment by plk** [comment]
This isn't a btparse issue, it's a biber issue and there is a related ticket open about the same sort of problem.

**Comment by plk** [comment]
Should be fixed in 2.9 dev (no need to update biblatex). I have finally re-done the latex decoding and made it a bit more semantic instead of just a raw regexp routine on the whole .bib file. It should avoid some of these sorts of issues in future. Can you check and I'll release 2.9.

**Comment by moewew** [comment]
The MWE works fine again with 2.9. Any chance these changes make looking into https://github.com/plk/biber/issues/185 possible again?

**Comment by moewew** [comment]
People are complaining about performance again: https://tex.stackexchange.com/q/401818/35864 Apparently Biber 2.8 is considerably slower with entries with many names than 2.7. Does that have to do with the new name disambiguation? (Which is disabled on the `biblatex` side here.)

**Comment by plk** [comment]
Yes, it's the `uniquename` disambiguation I think. Can't really be helped if we want completely generalised name handling and that is a huge name list. A source map would fix it for intermediate compiles.

**Comment by moewew** [comment]
It was my first guess, because it is definitely the number of names that slows things down. But I'm wondering why it still happens even if disambiguation is not requested by `biblatex`. For this particular user things would then probably improve if disambiguation is done only if it is explicitly requested.

**Comment by plk** [comment]
I have refactored it so that is `uniquename` isn't requested, it will skip some routines internally. This results in a large speedup on such long name lists. In my tests, down from 9 seconds in the critical sub to 1 second. Will update the TSE thread.

**Comment by moewew** [comment]
Very good. Was there also room for other speed improvements? If the option is turned on in a lager document, things could still take quite long.

**Comment by plk** [comment]
Looking at the case when the option in enabled still

**Comment by plk** [comment]
@moewew - You'll be pleased to know that I have just implemented a huge speed up of about for when `uniquename` is enabled in 2.9. With it enabled for the TSE name list example, runs are down from about 10 mins to 24 seconds ...
